### ISSUE TITLE
Add better formatting to readme.md

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/jelly-beats#176]
> Note: Issue open for multiple contributors, Happy hacktober fest :tada: 

We need better formatting for the `readme.md` file:

- Add spaces and new lines when it's required.
- Add special format to script codes or commands.
- Add titles and respect size hierarchy.
- Fix typos.

**Comment by jervis446** [comment]
can i work on it?

**Comment by btzr-io** [comment]
@jervis446 If you find any more improvements, then yes!
