### ISSUE TITLE
Add better formatting for the pull request template

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/jelly-beats#179]
> Note: Issue open for multiple contributors, Happy hacktober fest :tada: 

We need better formatting for the pull request template file:

- Remove unnecessary text or just make it easy to read and understand.
- Add spaces and new lines when it's required.
- Add special format to script codes or commands.
- Add titles and respect size hierarchy.
- Fix typos.

**Comment by robotenique** [comment]
I'll take this

**Comment by btzr-io** [comment]
@robotenique  Feel free to open a pull request, this issue is open for multiple contributors because we always can improve something.
