### ISSUE TITLE
Redesign player

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/jelly-beats#182]
We need your help to redesign the current player component:
- Improve buttons space (add more space where is necessary or remove unnecessary spacing).
- Add more organization or just improve the layout structure.
- Simplify the complexity so it's more easy to interact. 
- Or just leave your feedback in a comment below.
#### Current design:
![player](https://user-images.githubusercontent.com/14793624/47058468-65487080-d182-11e8-82c6-25ca26446b74.png)

**Comment by seanyesmunt** [comment]
Some of my initial thoughts
- Maybe remove some of the elements altogether when nothing is loaded? 
- It looks like the content isn't vertically centered since the scrub bar is slightly below the center line.

I like it a lot though. Pretty simple. Maybe tooltips over the icons?
