### ISSUE TITLE
Don't show the player if there is no track selected

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/jelly-beats#186]
* **I'm submitting a ...**
 - [ ] bug report
 - [x] feature request

* **What is the current behavior?**
The player is always show on screen.

* **What is the expected behavior?**
Don't show the player unless is necessary.

Please see: https://github.com/btzr-io/jelly-beats/issues/182#issuecomment-430481507

**Comment by rogelio-o** [comment]
Can I work on this?

**Comment by btzr-io** [comment]
@rogelio-o  It's all yours!
