### ISSUE TITLE
SoundBytez.io API integration

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/jelly-beats#333]
>  Decentralized Music Sharing - https://soundbytez.io/

The API integration of soundBytez.io should make possible the following features:

- [ ] Sharing / embedded  content.
- [x] Streaming (free claims).

**Comment by kcseb** [comment]
Once my team and I get the code base sorted regarding uploading and embedding audio types, I will look further into integrating the two services. Our priority at the moment is to get SoundBytez in an operational state before looking for any integration or third-party interaction.

Will keep this updated as we move forward, Thank you!

**Comment by kcseb** [comment]
In the current state of SoundBytez, I believe we would be willing to start talk of API integration. At the moment, it would be limited to sharing the content. 

We are still working on embedding content using an audio-player in JSX. 

What all would you need from us (at SoundBytez) to begin integration with Jelly Beats?

**Comment by kcseb** [comment]
Update: We've added the ability to playback embedded audio. We pulled a piece that was claimed on Jelly Beats (https://soundbytez.io/@FeralLogic:e/FeralLogic0x0001) and successfully played it back on SoundBytez. 

As I asked before, what all would you need from us to begin integration with Jelly Beats? 

Let us know, Thank you!

**Comment by btzr-io** [comment]
@kcseb Hi, I'm stuck refactoring the track list component so I can't get much integrated until I finish that..
I'm guessing `soundbytez` follows the same api as speech, and looks like the direct link is working so I think I can work with that for now :v:

**Comment by btzr-io** [comment]
Also I been looking for a way to extend the claim metadata and support something similar like https://en.wikipedia.org/wiki/ID3

@kcseb  So far the only decentralized way to achieve this that I know is to include the additional metadata inside the claim description.

**Comment by btzr-io** [comment]
Never mind, there is going to be new metadata for claims and channels :+1:

**Comment by kcseb** [comment]
Regarding metadata;

SoundBytez is currently pulling the claim author (spee.ch channel name) and claim name (spee.ch claim/file name) as the "track artist" and "track title".

This can be seen on our new audio-player on mostly any claim that has been published from a channel.

If the person has not uploaded to a channel, it will simply display "No Music Artist Found".

We're likely going to add a message on the upload prompt urging individuals to publish to channels/collections to better help the overall design.

**Comment by btzr-io** [comment]
@kcseb Hi, I'm now working on this (streaming) and just have some questions:
- Are you using the same api routes as `spee.ch`?
- What happens if the file is not ready yet on `soundbytez`? Do I need to wait until the file is fully downloaded or does it start streaming right a way?

Anyway if your api is similar to `spee.ch`, this should work:
`https://soundbytez.io/${channelName}:${channelId}/${name}.mp3`

**Comment by kcseb** [comment]
Yes, we are using the same API as spee.ch. 

If a file is not available yet on SoundBytez, it will not play, same as Spee.ch. 

If you're referring to download availability, you wont have to wait for the full download to finish, it will begin playing whatever is available in the buffer as it becomes available.

**Comment by btzr-io** [comment]
@kcseb Awesome thanks, I'm almost done just a few minor changes left :v:

**Comment by btzr-io** [comment]
This is already implemented but will be replaced by: #441
