### ISSUE TITLE
Windows build errors

### ISSUE THREAD

**Issue by kodxana** [btzr-io/jelly-beats#366]
This repository's issues are reserved for feature requests and bug reports.

- **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request

* **What is the current behavior?**

Missing node_modules not allow to build app on Windows OS

- **Please tell us about your environment:**

  - [x] Windows
  - [ ] MacOS
  - [ ] Linux

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Can be fixed by add 
babel-loader, react-native, register-scheme, @babel/preset-env, babel-loader 

Into package.json :)

**Comment by btzr-io** [comment]
You need to set an environment variable:
`ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES = true`
https://github.com/electron-userland/electron-builder/issues/2236#issuecomment-340204374

**Comment by btzr-io** [comment]
We should probably add this to the  docs.

**Comment by btzr-io** [comment]
Also this is for all OS not just windows :+1:
